apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-deployment
  labels:
    app: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure-container
        image: 
        ports:
        - containerPort: 8080
