apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-deployment
  labels:
    app: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
      - name: finance
        image:  vvek24/bankfinance:latest
        ports:
        - containerPort: 8081
